# Generated by Django 2.2.16 on 2020-10-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hghfhgjh",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jhgfjhghfjg", models.BigIntegerField()),
                ("tutututu", models.GenericIPAddressField()),
                ("jhjhkjhkjhkjhkh", models.GenericIPAddressField()),
            ],
        ),
    ]
