# Generated by Django 2.2.16 on 2020-10-23 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebhvfhjf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hghfhgjh',
            name='tutututu',
        ),
    ]
