# Generated by Django 2.2.16 on 2020-10-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homebhvfhjf", "0002_remove_hghfhgjh_tutututu"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hghfhgjh",
            name="jhjhkjhkjhkjhkh",
        ),
    ]
